#!/bin/bash

if [[ -z "$1" ]]; then
  echo >&2 "USAGE: $0 /path/to/spar/root"
  exit 1
fi

if [[ ! -f "$1/.build" ]]; then
  echo >&2 "$1: does not look like a valid spar root (no .build file)"
  exit 1
fi

sudo chroot "$1" /tools/bin/env -i \
         HOME=/root                \
         TERM="$TERM"              \
         PS1='\u:\w\$ '            \
         PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin \
         /tools/bin/bash --login +h
